### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by pastordee** [nillnil/flutter_base#1]
Hello thank you for your package I really like it I was wondering is there any timeframe on null safety

and also how can sort out these errors in flutter 2.0.2

MediaQuery.of(context, nullOk: true)?.size;  nullOk is giving and error 
Theme.of(context, shadowThemeOnly: true); shadowThemeOnly is also giving an error

**Comment by nillnil** [comment]
I'm sorry I didn't reply to you in time. Now you can use the latest code to solve the safety problem, it's update flutter to v2.0.3.

**Comment by nillnil** [comment]
fixed
